"""PSS parser for ml-hpi (PSS component declarations -> IDL).

Parses PSS source generated by ``GenPSS`` back to ``MlHpiDoc``. The parser
handles the structured output produced by GenPSS, including ``// ml-hpi:``
pragma comments for round-trip fidelity.

When ``zuspec-fe-pss`` is available, it is used for robust parsing. Otherwise,
a targeted text parser handles the GenPSS output format.
"""
from __future__ import annotations
import re
from pathlib import Path
from typing import Union

from ml_hpi.model import (
    Interface, Method, MethodAttr, Param, Member, MlHpiDoc, MlHpiSpec,
)
from .parse_base import Parser, pss_scalar_to_ml


# Regex patterns for GenPSS output format
_RE_PACKAGE = re.compile(r"^\s*package\s+(\w+)\s*\{")
_RE_COMPONENT = re.compile(r"^\s*component\s+(\w+)\s*(?::\s*(\w+))?\s*\{")
_RE_FUNCTION = re.compile(
    r"^\s*(target\s+)?function\s+(\S+)\s+(\w+)\s*\(([^)]*)\)\s*;"
    r"(?:\s*//\s*ml-hpi:\s*(.*))?"
)
_RE_MEMBER_FIELD = re.compile(r"^\s*(\w+)\s+(\w+)\s*;")
_RE_MEMBER_ARRAY = re.compile(r"^\s*array\s*<\s*(\w+)\s*,\s*\*\s*>\s+(\w+)\s*;")
_RE_CLOSE = re.compile(r"^\s*\}")


class ParsePSS(Parser):
    """Parse PSS ``component`` declarations into an ``MlHpiDoc``."""

    def parse(self, source: Union[str, Path]) -> MlHpiDoc:
        source_str = str(source) if isinstance(source, Path) else source
        path = Path(source_str)
        if path.is_file():
            text = path.read_text()
        else:
            text = source_str

        interfaces: list[Interface] = []
        current_pkg = ""
        current_comp: dict | None = None
        # Track component names in current package for member type resolution
        comp_names: set[str] = set()

        for line in text.splitlines():
            # Package declaration
            m = _RE_PACKAGE.match(line)
            if m:
                current_pkg = m.group(1)
                continue

            # Component declaration
            m = _RE_COMPONENT.match(line)
            if m:
                if current_comp is not None:
                    interfaces.append(self._build_interface(current_comp, current_pkg, comp_names))
                comp_name = m.group(1)
                extends_short = m.group(2)
                extends = f"{current_pkg}.{extends_short}" if extends_short and current_pkg else extends_short
                comp_names.add(comp_name)
                current_comp = {
                    "name": f"{current_pkg}.{comp_name}" if current_pkg else comp_name,
                    "extends": extends,
                    "methods": [],
                    "members": [],
                }
                continue

            # Function declaration
            m = _RE_FUNCTION.match(line)
            if m and current_comp is not None:
                is_target = m.group(1) is not None
                rtype_pss = m.group(2)
                fname = m.group(3)
                params_str = m.group(4).strip()
                pragma = m.group(5)

                rtype = pss_scalar_to_ml(rtype_pss)
                params = []
                if params_str:
                    for p in params_str.split(","):
                        p = p.strip()
                        parts = p.rsplit(None, 1)
                        if len(parts) == 2:
                            params.append({"name": parts[1], "type": pss_scalar_to_ml(parts[0])})

                # Parse ml-hpi pragma comments
                blocking = True if is_target else False  # default
                log_level = None
                if pragma:
                    for kv in pragma.split(","):
                        kv = kv.strip()
                        if "=" in kv:
                            k, v = kv.split("=", 1)
                            k, v = k.strip(), v.strip()
                            if k == "blocking":
                                blocking = v.lower() == "true"
                            elif k == "log_level":
                                log_level = v.lower()

                current_comp["methods"].append({
                    "name": fname,
                    "rtype": rtype,
                    "params": params,
                    "target": is_target,
                    "blocking": blocking,
                    "log_level": log_level,
                })
                continue

            # Array member
            m = _RE_MEMBER_ARRAY.match(line)
            if m and current_comp is not None:
                mem_type = m.group(1)
                mem_name = m.group(2)
                if current_pkg:
                    mem_type = f"{current_pkg}.{mem_type}"
                current_comp["members"].append({
                    "name": mem_name,
                    "kind": "array",
                    "type": mem_type,
                })
                continue

            # Field member (must come after array to avoid matching array lines)
            m = _RE_MEMBER_FIELD.match(line)
            if m and current_comp is not None:
                type_name = m.group(1)
                field_name = m.group(2)
                # Only treat as member if the type is a known component name
                if type_name in comp_names:
                    if current_pkg:
                        type_name = f"{current_pkg}.{type_name}"
                    current_comp["members"].append({
                        "name": field_name,
                        "kind": "field",
                        "type": type_name,
                    })
                continue

        # Finalize last component
        if current_comp is not None:
            interfaces.append(self._build_interface(current_comp, current_pkg, comp_names))

        return MlHpiDoc(spec=MlHpiSpec(interfaces=interfaces))

    def _build_interface(self, comp: dict, pkg: str, comp_names: set[str]) -> Interface:
        methods = []
        for m in comp["methods"]:
            attrs = []
            if m.get("target"):
                attrs.append(MethodAttr(target=True))
            if m.get("blocking") is not None:
                attrs.append(MethodAttr(blocking=m["blocking"]))
            if m.get("log_level") is not None:
                attrs.append(MethodAttr(log_level=m["log_level"]))
            methods.append(Method(
                name=m["name"],
                rtype=m["rtype"],
                params=[Param(**p) for p in m["params"]],
                attr=attrs,
            ))

        members = [
            Member(name=m["name"], kind=m["kind"], type=m["type"])
            for m in comp["members"]
        ]

        return Interface(
            name=comp["name"],
            extends=comp["extends"],
            methods=methods,
            members=members,
        )
