/* Auto-generated by ml-hpi GenC — do not edit */
#ifndef TB_REGIF_DPI_H
#define TB_REGIF_DPI_H

#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

/* DPI exports — implemented in SystemVerilog, called from C */
extern void tb_RegIf_write32(int root_id, int path, uint64_t addr, uint32_t data, void *cb);
extern void tb_RegIf_read32(int root_id, int path, uint64_t addr, void *cb);

/* Completion imports — implemented in C, called from SystemVerilog */
void tb_RegIf_write32_complete(void *cb);
void tb_RegIf_read32_complete(void *cb, uint32_t rval);

#ifdef __cplusplus
}
#endif

#endif /* TB_REGIF_DPI_H */
