// tb_test_pkg.sv — test-specific DPI package (not generated by ml-hpi).
// Provides the test-control entry/exit points that connect C test logic to SV.
package tb_test;

  // Package init: C captures the tb_test package scope at elaboration time.
  import "DPI-C" context function int tb_test_init();
  int __pkg_init = tb_test_init();

  // Entry point: SV calls into C test logic after registering the root instance.
  import "DPI-C" function void ml_hpi_test_start(int root_id);

  // Exit point: C calls this to end simulation.
  export "DPI-C" function ml_hpi_test_finish;
  function automatic void ml_hpi_test_finish();
    $finish;
  endfunction

endpackage
